spring:
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
  datasource:
    #相对位置配置方式
    url: jdbc:sqlite:E:/fms.db
    driver-class-name: org.sqlite.JDBC
  # 文件上传大小
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 500MB

# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.shiva.entity

api:
  sourceCode: SERVERUI,TERMINAL
  privateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDErp/AL9GiFluUdOF9ZV3BNYTuyT6yaMlQPYoNYtWFOIKjbTPwNWot9DEJxq0DrQVAvoagpxkLXiteLetP259xrMtjT/Y+RsqTZik1p2/hHr2y2mb6jfazVMyKONuEP9w1IGr4pAA0ZPsd41slXQnrylmw9DiFxLyMbClp7Zu38AsK1KKdTiyq58fVBr9aRXreAnTwT/96Uo5Lwscw2VHu1yPkJwqQmtcdJLILst1ZzqYPNTiUFFjk8Nccc5WJ47FTCHh7D7U0hM7vdK2s5UETOquBgF5+Vjo+uFOVkWx63zrPIGJQdEMW6ckRqEKOwRMMlG289NJsyYDzihPSpD7tAgMBAAECgf8sM5sIuD7+P3+ImWacUF7St84GIGddKJXzg5zHQzvKX4J0BNKFOoz3pMdgjTTda2ttdtuXg4/H/j/A2aIZtspz48fz8De8T8YmBOC1g4VL8HqPYh+gc+DKbLvPZaJ4a51m/dEMmJu3bvpV8G1HPKGXwp3dFdKNCmWZsehpkKd/amNtV/T8+F5QoEl0DsBbNRYnC+ugr46PtyHKgcEOeCRXOdq4abmuYBFQNSgHPLSL/aKFdKrlV893DJgwODGK647pgtYrU2UAzqyLe3zTJFs9vC3LEtqkYOIrA+g8o5c2rRJ5FonyLVI4V5oynaggixufjRBd+ziip69nUV20pSECgYEA608+rPKvLQISZClKQXI7lS7kLgdb/lXudBdixL6WLa9daiW5RHeH5pi6DNkBCwrmJBadKLF/R6O+8El9qq8zMnHQPp3Klxns3JK1UH3ZeTsfuEXQJ9mX4W5cQW1C5CQa0jcplTl5FmW3054rqYMOrPKUNqOPr38seCeOJCviuAUCgYEA1fni3CmcObf8iZVwO/2UiLe4zF01VXmAdfxvFeQRUBshpTfAVUCsO8Qn41UiPz8OQy2WCPsoBj5Ci5auNhKLj1kM2Rlb0sbu0MIYghVnOrf1MBEI/qgolBVVgcI0mjMrjeZ0OhoGcdJu93+Raroe0CZ+fhBLYXHfPe5hhaWFJ8kCgYEAglS7BznHsush2p5QBZ3KyJ9XPPNQjbd0wpItX4GcVqN53xAT5Is8F4niCrmq7T3VKInp9B8Tu09Ds31RAFfXyInnaLcm/bgbTDRp/rIl4RLRR9RLLbdEe1UP/iERWqFwxZxOCNvzaGdggPJrhpETcNFPLFA9hluu+sIV5Yz1Hy0CgYEAszvNu31fTzm+X8C9coLGmH7MXOL2edJ8uFfq9PtFRUR0umAoy0CRBL8aamI1faTj3YGh24QF0rT0KNjetIx0Om7tRCzprXTVNihfPxeOkLDmwIyEbEuPMfts1HRIe6HBKeuQD9sc6trJ+Kbyt+OPS+vyqMYdXlJ0HPxA1CIBl4ECgYAQPIYmbEQtXF5fS4dCfpIuMgmeHrr9xE8kx/gmJGrgRFeH5XUA14GLoz1JxESw0l4kifzCgTeewKjuc658xP+QpBM7TqB7adKsXWoCVf9fee/JqoHz9SebWORKQoxofOBimv81ABhnVeZV4XirjfvK2DeCclOl55GBMyYe3jm4ZA==
